name: Build and Deploy C Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (gcc, make, cJSON)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcjson-dev

    - name: Build with make
      working-directory: ./src
      run: make

    - name: Setup PEM key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY_PEM }}" > ~/.ssh/deploy_key.pem
        chmod 400 ~/.ssh/deploy_key.pem

    - name: Deploy binary to remote server
      run: |
        scp -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no -P $DEPLOY_PORT \
          src/http_app ubuntu@$DEPLOY_HOST:/home/ubuntu/kuttalk_server

    - name: Restart server remotely
      run: |
        ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no -p $DEPLOY_PORT \
          ubuntu@$DEPLOY_HOST << 'EOF'
        pkill -f kuttalk_server || true
        nohup /home/ubuntu/kuttalk_server > /home/ubuntu/kuttalk.log 2>&1 &
        EOF
