name: Build and Deploy C Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (gcc, cmake, cJSON, MySQL client)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libcjson-dev libmysqlclient-dev pkg-config

      - name: Configure with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: |
          cd build
          cmake --build . --config Release

      - name: Ensure remote deploy directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY_PEM }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            rm -rf /home/ubuntu/kuttalk_server
            mkdir -p /home/ubuntu/kuttalk_server

      - name: Copy binary to remote via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY_PEM }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "build/kut_talk_api"
          target: "/home/ubuntu/kuttalk_server/"

      - name: Restart server remotely
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_KEY_PEM }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            pkill -f kut_talk_api || true
            nohup /home/ubuntu/kuttalk_server/kut_talk_api > /home/ubuntu/kuttalk.log 2>&1 &
